.. _ssp-information-system-categorization:

Information System Categorization
=================================

.. only:: fips_199_low

   The :term:`FIPS 199` Categorization for this system is: **LOW** [#]_

.. only:: fips_199_moderate

   The :term:`FIPS 199` Categorization for this system is: **MODERATE** [#]_

.. only:: fips_199_high

   The :term:`FIPS 199` Categorization for this system is: **HIGH** [#]_


.. rubric:: Footnotes

.. only:: fips_199_low

   .. [#] From :term:`FIPS 199`: The loss of confidentiality, integrity, or
          availability could be expected to have a **limited** adverse effect
          on organizational operations, organizational assets, or individuals.

          This means that the loss of confidentiality, integrity, or
          availability might:

            1. cause a degradation in mission capability to an extent and
               duration that the organization is able to perform its primary
               functions, but the effectiveness of the functions is noticeably
               reduced;
            2. result in minor damage to organizational assets;
            3. result in minor financial loss; or
            4. result in minor harm to individuals.

.. only:: fips_199_moderate

   .. [#] From :term:`FIPS 199`: The loss of confidentiality, integrity, or
          availability could be expected to have a **serious** adverse effect
          on organizational operations, organizational assets, or individuals.

          This means that the loss of confidentiality, integrity, or
          availability might:

            1. cause a significant degradation in mission capability to an
               extent and duration that the organization is able to perform its
               primary functions, but the effectiveness of the functions is
               significantly reduced;
            2. result in significant damage to organizational assets;
            3. result in significant financial loss; or
            4. result in significant harm to individuals that does not involve
               loss of life or serious life threatening injuries.

.. only:: fips_199_high

   .. [#] From :term:`FIPS 199`: The loss of confidentiality, integrity, or
          availability could be expected to have a severe or catastrophic
          adverse effect on organizational operations, organizational assets,
          or individuals.

          This means that the loss of confidentiality, integrity, or
          availability might:

            1. cause a severe degradation in or loss of mission capability to
                an extent and duration that the organization is not able to
                perform one or more of its primary functions;
            2. result in major damage to organizational assets;
            3. result in major financial loss; or
            4. result in severe or catastrophic harm to individuals involving
               loss of life or serious life threatening injuries.
