.. _ssp-operational-status:

Operational Status
==================

.. only:: operational_status_operational

   The Operational Status of this information system is: **Operational**

.. only:: operational_status_under_development

   The Operational Status of this information system is: **Under Development**

.. only:: operational_status_major_modification

   The Operational Status of this information system is: **Major Modification**
