.. _ssp-system-type:

System Type
===========

.. only:: system_type_major_application

   The System Type of this information system is: :term:`Major Application`

.. only:: system_type_general_support_system

   The System Type of this information system is: :term:`General Support System`

.. IMPORTANT::

   If the system contains :term:`minor applications`, list them in
   :ref:`ssp-system-description`
